# version: '3.8'

# services:
#   backend:
#     build:
#       context: ./backend
#       dockerfile: Dockerfile.prod
#     environment:
#       NODE_ENV: production
#       DATABASE_URL: ${DATABASE_URL}
#     restart: always
    
#   frontend:
#     build:
#       context: ./frontend
#       dockerfile: Dockerfile.prod
#     restart: always

#   nginx:
#     image: nginx:alpine
#     ports:
#       - "80:80"
#       - "443:443"
#     volumes:
#       - ./nginx.conf:/etc/nginx/nginx.conf
#     depends_on:
#       - backend
#       - frontend
